# Generated by Django 2.2 on 2019-09-22 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('Date', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('Title', models.CharField(max_length=50)),
                ('Depaetment', models.CharField(max_length=50)),
                ('Descripion', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
