# Generated by Django 2.2 on 2019-09-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='story',
            new_name='storyModel',
        ),
    ]
